name: azure_maps_jupyter-dev
channels:
  - conda-forge
dependencies:
  - pip
  - wheel
  - flake8
  - jupyterlab
  - ipywidgets
  - xyzservices
  - branca
  - traittypes
  - jupyter-packaging~=0.7.9
  - pandas
